### ISSUE TITLE
Private repositories

### ISSUE THREAD

**Issue by markgould** [ams0/acr-task-github-action#3]
Is it possible to make this work with private GitHub repos? I'm new to GitHub actions (coming from Azure DevOps) but it looks like an optional parameter could be added to pass a PAT.

https://github.com/Azure/azure-cli/issues/11455#issuecomment-560500505

I'd be happy to try implementing and submit a PR if you'd like.

**Comment by ams0** [comment]
Hi there, I published a v2 version: https://github.com/ams0/acr-task-github-action/tree/v2 that adds the github token parameter (and I cleaned up the readme). 

It was a bit confusing because the `--git-access-token` flag is only available for the `task` command, not the `build` command. I found out that using the form `token`@github.com/private/private.git` does the trick. 

Let me know if it works for you, I tried it on a private fork of https://github.com/Azure-Samples/openhack-containers and seems to work.

**Comment by antempus** [comment]
I've tried this with the changes you've added, but I cannot seem to get the PAT to work properly. Still getting the same error. 

I'm not really familiar with ACR's task runner, but is there a way to use an SSH key or setting up an OAuth application to go around PAT, I was always under the impression pat was coupled with your username
